import type { Metadata } from "next";
import "./globals.css";
import 'swiper/css/bundle';



export const metadata: Metadata = {
    title: "Joki Helfi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased bg-[#0C0C0C]`}
                style={{ fontFamily: "'ArcaneNine', sans-serif" }}
            >
                {children}
            </body>
        </html>
    );
}
